✨Pixi recommendations
ampproject/amp.dev pull request #4355
Opened 2020-08-21 13:56 UTC by robinvanopstal

2020-08-24 12:00 UTC, matthiasrohmer requested changes

2020-08-24 12:00 UTC, matthiasrohmer commented on pixi/src/ui/PageExperience.js
> +
This still needs to be done 😁

2020-08-24 12:16 UTC, matthiasrohmer approved these changes

2020-08-24 12:16 UTC, merged

2020-08-25 08:45 UTC, robinvanopstal commented on pixi/src/checks/AmpLinterCheck.js
>          usesHttps: apiResult.url.startsWith('https:'),
`result`