added Web Story discovery guide
ampproject/amp.dev pull request #4755
Opened 2020-09-30 22:45 UTC by CrystalOnScript

2020-10-01 02:08 UTC, pbakaus requested changes
Cool, thanks! Left a bunch of comments.

2020-10-01 02:08 UTC, pbakaus commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +# HTML markup
I think these can also probably moved into the html metadata section, they technically all are

2020-10-01 02:08 UTC, pbakaus commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +Including [schema.org](https://schema.org/) structured data vocabulary defines important information about your Web Story that allows third-party platforms, such as search engines, to display and ind
Can we link to https://search.google.com/test/amp somewhere here? It's great for testing schema.org data.

2020-10-01 02:08 UTC, pbakaus commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +Including [Open Graph protocol](https://ogp.me/) enables Web Stories to become a rich object in a social graph.
I think it's fine calling out that this is important for Facebook.

2020-10-05 19:19 UTC, CrystalOnScript commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +A URL to an image used as the [Web Story poster](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)). Used as
No problem, I'll update the language - but just an FYI, pre-embed is a word I copied from the public-facing spread sheet

2020-10-05 19:23 UTC, CrystalOnScript commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +## Image alt-text
Are those metadata or a11y features?

2020-10-05 21:41 UTC, pbakaus commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +## Image alt-text
Both :)

2020-10-06 00:43 UTC, pbakaus commented on pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
> +A URL to an image used as the [Web Story poster](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)). Used as
ty! Should ping the spreadsheet too :)

2020-10-08 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amp.dev?pullRequest=4755) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amp.dev?pullRequest=4755) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amp.dev?pullRequest=4755) it.</sub>

2020-10-15 20:00 UTC, pbakaus approved these changes

2020-10-15 20:29 UTC, merged